environments:
  default: &default
    model_name: fvg
    aws_role: 'AmazonSageMakerFullAccess'
  local:
    <<: *default
    instance_type: local
    #model_data_path: 'file://build/model.tar.gz'
    model_data_path: 'file:///home/srivatsas/work/repos/personal/mlserve/fvg/build/model.tar.gz'
  production:
    <<: *default
    instance_type: ml.t2.medium
    model_data_path: s3://sagemaker-pytorch-text-classification/model.tar.gz