environments:
  default: &default
    model_name: pytorch-text-classification
    aws_role: 'AmazonSageMakerFullAccess'
  local:
    <<: *default
    instance_type: local
    model_data_path: 'file://build/model.tar.gz'
  production:
    <<: *default
    instance_type: ml.t2.medium
    model_data_path: ''